services:
  - type: web
    name: luntra-calculator-mvp
    env: python
    repo: https://github.com/bdusape/luntra-calculator-mvp
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true --server.address 0.0.0.0
    plan: free
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"